reddit_actual/config/routes.rb
Rails.application.routes.draw do

   root 'posts#index'

     get 'posts' => 'posts#index'
     get 'posts/new' => 'posts#new'

     post 'posts' => 'posts#create'

     get 'users' => 'users#index'
     get 'users/new' => 'users#new'
     post 'users' => 'users#create'

     get 'users/:id' => 'users#show'

end

reddit_actual/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user

	validates(:title, {
	:presence => true,
	:length => {:maximum => 50}
		})
	validates(:body, {
    :presence => true, 
    :length => {:maximum => 140}
  })
end

reddit_actual/app/models/user.rb
class User<ActiveRecord::Base

	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :posts, dependent: :destroy
end

reddit_actual/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params["post"].permit(:title, :body))
		@post.user = User.last
		@post.score = 0
		
		@post.save

		redirect_to '/posts'
	end 
end

reddit_actual/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private
		params.require(:user).permit(:username, :password, :password_confirmation)
	end
end

reddit_actual/app/controllers/users_controller.rb
class UsersController <ApplicationController
	before_action :authenticate_user!

	def index
		@users = User.all
	end

	def show
    	@user = User.find(params[:id])
    	@posts = @user.posts
  	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(params["user"].permit(:username, :score))
		@user.save

		redirect_to '/users'
	end
end

reddit_actual/app/views/users/index.html.erb
<h1>Users!</h1>
<p>Users are listed here</p>

<%= link_to '+ New User', users_new_path %>

<ol>
<% @users.each do |user| %>
  <li><%= user.username %></li>
<% end %>
</ol>

reddit_actual/app/views/users/new.html.erb
<h1>New User!</h1>

<%= form_for @user, :url => '/users' do |f| %>
	<%= f.label :username %>:
	<%= f.text_field :username %><br />

	<%= f.label :karma %>:
	<%= f.text_field :karma %><br />
	<%= f.submit %>
<% end %>

reddit_actual/app/views/users/show.html.erb
<div class="user_profile">
	<div class="username"><%= @user.username %></div>

</div>

<table class="post_list">
<% @posts.each do |post| %>
  <tr>
    <td>
        <%= post.body %>
    </td>
  </tr>
<% end %>
</table>